DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'public') THEN
        EXECUTE 'CREATE SCHEMA public AUTHORIZATION ' || quote_ident(current_user);
    END IF;
END
$$;
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER SCHEMA public OWNER TO ' || quote_ident(current_user);
    EXCEPTION WHEN insufficient_privilege THEN
        RAISE NOTICE 'Insufficient privileges to alter schema.';
    END;
END $$;
SET search_path TO public;

DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN (
        SELECT tablename FROM pg_tables WHERE schemaname = 'public'
        AND tablename IN (
            'InformationDepotCabinetContacts','InformationDepotCabinetRoles','InformationDepotCabinets',
            'TitulairePays','InventeurPays','DeposantPays',
            'InformationsDepot','BrevetCabinets','BrevetTitulaires','BrevetDeposants','BrevetInventeurs','BrevetClients',
            'Contacts','UserRoles','Users','Roles',
            'NumeroPays','Statuts','Pays',
            'Titulaires','Deposants','Inventeurs','Brevets',
            'ClientCabinets','Cabinets','Clients',
            'Logs'
        )
    ) LOOP
        EXECUTE format('DROP TABLE IF EXISTS %I CASCADE;', r.tablename);
    END LOOP;
END $$;

CREATE TABLE "Cabinets" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom_cabinet" TEXT NOT NULL,
    "adresse_cabinet" TEXT NULL,
    "code_postal" TEXT NULL,
    "pays_cabinet" TEXT NULL,
    "email_cabinet" TEXT NULL,
    "telephone_cabinet" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "type" INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE "Clients" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom_client" TEXT NOT NULL,
    "reference_client" TEXT NULL,
    "adresse_client" TEXT NULL,
    "code_postal" TEXT NULL,
    "pays_client" TEXT NULL,
    "email_client" TEXT NULL,
    "telephone_client" TEXT NULL,
    "can_write" INTEGER NOT NULL DEFAULT 0,
    "can_read" INTEGER NOT NULL DEFAULT 1,
    "is_blocked" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Brevets" (
    "id_brevet" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reference_famille" TEXT NULL,
    "titre" TEXT NULL,
    "commentaire" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Inventeurs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NULL,
    "prenom" TEXT NULL,
    "adresse" TEXT NULL,
    "telephone" TEXT NULL,
    "email" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Deposants" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NULL,
    "prenom" TEXT NULL,
    "adresse" TEXT NULL,
    "telephone" TEXT NULL,
    "email" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Titulaires" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NULL,
    "prenom" TEXT NULL,
    "adresse" TEXT NULL,
    "telephone" TEXT NULL,
    "email" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Pays" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom_fr_fr" TEXT NOT NULL,
    "code_iso" TEXT NULL,
    "code_iso3" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Statuts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "description" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "NumeroPays" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "pays_code" TEXT NOT NULL,
    "numero" TEXT NOT NULL,
    "description" TEXT NULL,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "PaysId" INTEGER NULL
);

CREATE TABLE "Roles" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Description" TEXT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "canWrite" BOOLEAN NOT NULL DEFAULT FALSE,
    "canRead"  BOOLEAN NOT NULL DEFAULT TRUE,
    "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "isBlocked" BOOLEAN NOT NULL DEFAULT FALSE,
    "nom" TEXT NULL,
    "prenom" TEXT NULL,
    "lastLogin" TIMESTAMP NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "clientId" INTEGER NULL
);

CREATE TABLE "UserRoles" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "RoleId" INTEGER NOT NULL,
    "ClientId" INTEGER NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Contacts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NULL,
    "prenom" TEXT NULL,
    "email" TEXT NULL,
    "telephone" TEXT NULL,
    "role" TEXT NULL,
    "id_cabinet" INTEGER NULL,
    "id_client" INTEGER NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "emails_json" TEXT NOT NULL DEFAULT '[]',
    "phones_json" TEXT NOT NULL DEFAULT '[]',
    "roles_json" TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE "Logs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "level" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    "userId" TEXT NULL,
    "action" TEXT NULL,
    "table_name" TEXT NULL,
    "record_id" INTEGER NULL,
    "old_values" TEXT NULL,
    "new_values" TEXT NULL,
    "ip_address" TEXT NULL,
    "user_agent" TEXT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
    "details" TEXT NULL
);

CREATE TABLE "BrevetClients" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_client" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "BrevetInventeurs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_inventeur" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "BrevetDeposants" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_deposant" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "BrevetTitulaires" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_titulaire" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "BrevetCabinets" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_cabinet" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "ClientCabinets" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClientId" INTEGER NOT NULL,
    "CabinetId" INTEGER NOT NULL,
    "Type" TEXT NULL,
    "IsActive" INTEGER NOT NULL DEFAULT 1,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "InformationsDepot" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_brevet" INTEGER NOT NULL,
    "id_pays" INTEGER NULL,
    "id_statuts" INTEGER NULL,
    "numero_depot" TEXT NULL,
    "numero_publication" TEXT NULL,
    "numero_delivrance" TEXT NULL,
    "date_depot" TIMESTAMP NULL,
    "date_publication" TIMESTAMP NULL,
    "date_delivrance" TIMESTAMP NULL,
    "licence" INTEGER NOT NULL DEFAULT 0,
    "commentaire" TEXT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "InventeurPays" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "id_brevet" INTEGER NULL,
    "id_inventeur" INTEGER NOT NULL,
    "id_pays" INTEGER NOT NULL
);

CREATE TABLE "DeposantPays" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "id_brevet" INTEGER NULL,
    "id_deposant" INTEGER NOT NULL,
    "id_pays" INTEGER NOT NULL
);

CREATE TABLE "TitulairePays" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "id_brevet" INTEGER NULL,
    "id_pays" INTEGER NOT NULL,
    "id_titulaire" INTEGER NOT NULL
);

CREATE TABLE "InformationDepotCabinets" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "information_depot_id" INTEGER NOT NULL,
    "cabinet_id" INTEGER NOT NULL,
    "category" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "InformationDepotCabinetRoles" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "information_depot_cabinet_id" INTEGER NOT NULL,
    "role" TEXT NOT NULL
);

CREATE TABLE "InformationDepotCabinetContacts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "information_depot_cabinet_id" INTEGER NOT NULL,
    "contact_id" INTEGER NOT NULL
);
