ALTER TABLE "Contacts" ADD CONSTRAINT fk_contacts_client FOREIGN KEY (id_client) REFERENCES "Clients"(id) ON DELETE SET NULL;
ALTER TABLE "Contacts" ADD CONSTRAINT fk_contacts_cabinet FOREIGN KEY (id_cabinet) REFERENCES "Cabinets"(id) ON DELETE SET NULL;
ALTER TABLE "BrevetClients" ADD CONSTRAINT fk_brevetclients_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "BrevetClients" ADD CONSTRAINT fk_brevetclients_client FOREIGN KEY (id_client) REFERENCES "Clients"(id) ON DELETE CASCADE;
ALTER TABLE "BrevetInventeurs" ADD CONSTRAINT fk_brevetinventeurs_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "BrevetInventeurs" ADD CONSTRAINT fk_brevetinventeurs_inventeur FOREIGN KEY (id_inventeur) REFERENCES "Inventeurs"(id) ON DELETE CASCADE;
ALTER TABLE "BrevetDeposants" ADD CONSTRAINT fk_brevetdeposants_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "BrevetDeposants" ADD CONSTRAINT fk_brevetdeposants_deposant FOREIGN KEY (id_deposant) REFERENCES "Deposants"(id) ON DELETE CASCADE;
ALTER TABLE "BrevetTitulaires" ADD CONSTRAINT fk_brevettitulaires_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "BrevetTitulaires" ADD CONSTRAINT fk_brevettitulaires_titulaire FOREIGN KEY (id_titulaire) REFERENCES "Titulaires"(id) ON DELETE CASCADE;
ALTER TABLE "BrevetTitulaires" ADD CONSTRAINT fk_brevettitulaires_pays FOREIGN KEY (id_pays) REFERENCES "Pays"(id);
ALTER TABLE "InformationsDepot" ADD CONSTRAINT fk_informationsdepot_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "InformationsDepot" ADD CONSTRAINT fk_informationsdepot_pays FOREIGN KEY (id_pays) REFERENCES "Pays"(id);
ALTER TABLE "InformationsDepot" ADD CONSTRAINT fk_informationsdepot_statuts FOREIGN KEY (id_statuts) REFERENCES "Statuts"(id);
ALTER TABLE "InventeurPays" ADD CONSTRAINT fk_inventeurpays_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "InventeurPays" ADD CONSTRAINT fk_inventeurpays_inventeur FOREIGN KEY (id_inventeur) REFERENCES "Inventeurs"(id) ON DELETE CASCADE;
ALTER TABLE "InventeurPays" ADD CONSTRAINT fk_inventeurpays_pays FOREIGN KEY (id_pays) REFERENCES "Pays"(id);
ALTER TABLE "DeposantPays" ADD CONSTRAINT fk_deposantpays_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "DeposantPays" ADD CONSTRAINT fk_deposantpays_deposant FOREIGN KEY (id_deposant) REFERENCES "Deposants"(id) ON DELETE CASCADE;
ALTER TABLE "DeposantPays" ADD CONSTRAINT fk_deposantpays_pays FOREIGN KEY (id_pays) REFERENCES "Pays"(id);
ALTER TABLE "TitulairePays" ADD CONSTRAINT fk_titularepays_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "TitulairePays" ADD CONSTRAINT fk_titularepays_titulaire FOREIGN KEY (id_titulaire) REFERENCES "Titulaires"(id) ON DELETE CASCADE;
ALTER TABLE "TitulairePays" ADD CONSTRAINT fk_titularepays_pays FOREIGN KEY (id_pays) REFERENCES "Pays"(id);
ALTER TABLE "BrevetCabinets" ADD CONSTRAINT fk_brevetcabinets_brevet FOREIGN KEY (id_brevet) REFERENCES "Brevets"(id_brevet) ON DELETE CASCADE;
ALTER TABLE "BrevetCabinets" ADD CONSTRAINT fk_brevetcabinets_cabinet FOREIGN KEY (id_cabinet) REFERENCES "Cabinets"(id) ON DELETE CASCADE;
ALTER TABLE "ClientCabinets" ADD CONSTRAINT fk_clientcabinets_client FOREIGN KEY (ClientId) REFERENCES "Clients"(id) ON DELETE CASCADE;
ALTER TABLE "ClientCabinets" ADD CONSTRAINT fk_clientcabinets_cabinet FOREIGN KEY (CabinetId) REFERENCES "Cabinets"(id) ON DELETE CASCADE;
ALTER TABLE "UserRoles" ADD CONSTRAINT fk_userroles_user FOREIGN KEY (UserId) REFERENCES "Users"(id) ON DELETE CASCADE;
ALTER TABLE "UserRoles" ADD CONSTRAINT fk_userroles_role FOREIGN KEY (RoleId) REFERENCES "Roles"(Id) ON DELETE CASCADE;
ALTER TABLE "UserRoles" ADD CONSTRAINT fk_userroles_client FOREIGN KEY (ClientId) REFERENCES "Clients"(id) ON DELETE CASCADE;
ALTER TABLE "InformationDepotCabinets" ADD CONSTRAINT fk_infodepotcabinets_info FOREIGN KEY (information_depot_id) REFERENCES "InformationsDepot"(id) ON DELETE CASCADE;
ALTER TABLE "InformationDepotCabinets" ADD CONSTRAINT fk_infodepotcabinets_cabinet FOREIGN KEY (cabinet_id) REFERENCES "Cabinets"(id) ON DELETE CASCADE;
ALTER TABLE "InformationDepotCabinetRoles" ADD CONSTRAINT fk_infodepotcabinetroles_parent FOREIGN KEY (information_depot_cabinet_id) REFERENCES "InformationDepotCabinets"(id) ON DELETE CASCADE;
ALTER TABLE "InformationDepotCabinetContacts" ADD CONSTRAINT fk_infodepotcabinetcontacts_parent FOREIGN KEY (information_depot_cabinet_id) REFERENCES "InformationDepotCabinets"(id) ON DELETE CASCADE;
ALTER TABLE "InformationDepotCabinetContacts" ADD CONSTRAINT fk_infodepotcabinetcontacts_contact FOREIGN KEY (contact_id) REFERENCES "Contacts"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS IX_Clients_nom_client ON "Clients"(nom_client);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Cabinets_nom_cabinet ON "Cabinets"(nom_cabinet);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Statuts_description ON "Statuts"(description);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Pays_code_iso ON "Pays"(code_iso);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Pays_code_iso3 ON "Pays"(code_iso3);
CREATE UNIQUE INDEX IF NOT EXISTS IX_NumeroPays_pays_code ON "NumeroPays"(pays_code);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Roles_Name ON "Roles"(Name);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Users_username ON "Users"(username);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Users_email ON "Users"(email);
CREATE UNIQUE INDEX IF NOT EXISTS IX_Brevets_reference_famille ON "Brevets"(reference_famille);
CREATE UNIQUE INDEX IF NOT EXISTS IX_BrevetClients ON "BrevetClients"(id_brevet,id_client);
CREATE UNIQUE INDEX IF NOT EXISTS IX_BrevetInventeurs ON "BrevetInventeurs"(id_brevet,id_inventeur);
CREATE UNIQUE INDEX IF NOT EXISTS IX_BrevetDeposants ON "BrevetDeposants"(id_brevet,id_deposant);
CREATE UNIQUE INDEX IF NOT EXISTS IX_BrevetTitulaires ON "BrevetTitulaires"(id_brevet,id_titulaire);
CREATE UNIQUE INDEX IF NOT EXISTS IX_InventeurPays ON "InventeurPays"(id_brevet,id_inventeur,id_pays);
CREATE UNIQUE INDEX IF NOT EXISTS IX_DeposantPays ON "DeposantPays"(id_brevet,id_deposant,id_pays);
CREATE UNIQUE INDEX IF NOT EXISTS IX_TitulairePays ON "TitulairePays"(id_brevet,id_titulaire,id_pays);
CREATE UNIQUE INDEX IF NOT EXISTS IX_ClientCabinets ON "ClientCabinets"(ClientId,CabinetId);
CREATE UNIQUE INDEX IF NOT EXISTS IX_BrevetCabinets ON "BrevetCabinets"(id_brevet,id_cabinet);
CREATE INDEX IF NOT EXISTS IX_Contacts_Email ON "Contacts"(email);
CREATE INDEX IF NOT EXISTS IX_InformationsDepot_numero_depot ON "InformationsDepot"(numero_depot);
CREATE INDEX IF NOT EXISTS IX_InformationsDepot_numero_publication ON "InformationsDepot"(numero_publication);
CREATE INDEX IF NOT EXISTS IX_InformationsDepot_numero_delivrance ON "InformationsDepot"(numero_delivrance);
CREATE INDEX IF NOT EXISTS IX_InformationDepotCabinets_info ON "InformationDepotCabinets"(information_depot_id);
CREATE INDEX IF NOT EXISTS IX_InformationDepotCabinets_cabinet ON "InformationDepotCabinets"(cabinet_id);
CREATE INDEX IF NOT EXISTS IX_InformationDepotCabinetRoles_parent ON "InformationDepotCabinetRoles"(information_depot_cabinet_id);
CREATE INDEX IF NOT EXISTS IX_InformationDepotCabinetContacts_parent ON "InformationDepotCabinetContacts"(information_depot_cabinet_id);
