// countryNameToIso.js
const countryNameToIso = {
  "afghanistan": "AF",
  "afrique du sud": "ZA",
  "aland islands": "AX",
  "albania": "AL",
  "albanie": "AL",
  "algeria": "DZ",
  "algerie": "DZ",
  "allemagne": "DE",
  "american samoa": "AS",
  "andorra": "AD",
  "andorre": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antarctique": "AQ",
  "antigua and barbuda": "AG",
  "antigua-et-barbuda": "AG",
  "antilles neerlandaises": "AN",
  "arabie saoudite": "SA",
  "argentina": "AR",
  "argentine": "AR",
  "armenia": "AM",
  "armenie": "AM",
  "aruba": "AW",
  "australia": "AU",
  "australie": "AU",
  "austria": "AT",
  "autriche": "AT",
  "azerbaidjan": "AZ",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bahrein": "BH",
  "bangladesh": "BD",
  "barbade": "BB",
  "barbados": "BB",
  "belarus": "BY",
  "belgique": "BE",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "bermudes": "BM",
  "bhoutan": "BT",
  "bhutan": "BT",
  "bolivia": "BO",
  "bolivie": "BO",
  "bosnia and herzegovina": "BA",
  "bosnie-herzegovine": "BA",
  "botswana": "BW",
  "bouvet island": "BV",
  "brazil": "BR",
  "bresil": "BR",
  "british indian ocean territory": "IO",
  "british virgin islands": "VG",
  "brunei darussalam": "BN",
  "bulgaria": "BG",
  "bulgarie": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cambodge": "KH",
  "cambodia": "KH",
  "cameroon": "CM",
  "cameroun": "CM",
  "canada": "CA",
  "cap-vert": "CV",
  "cape verde": "CV",
  "cayman islands": "KY",
  "central african": "CF",
  "chad": "TD",
  "chile": "CL",
  "chili": "CL",
  "china": "CN",
  "chine": "CN",
  "christmas island": "CX",
  "chypre": "CY",
  "cocos (keeling) islands": "CC",
  "colombia": "CO",
  "colombie": "CO",
  "comores": "KM",
  "comoros": "KM",
  "cook islands": "CK",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  "croatia": "HR",
  "croatie": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech republic": "CZ",
  "danemark": "DK",
  "democratic people's republic of korea": "KP",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "dominique": "DM",
  "ecuador": "EC",
  "egypt": "EG",
  "egypte": "EG",
  "el salvador": "SV",
  "emirats arabes unis": "AE",
  "equateur": "EC",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "erythree": "ER",
  "espagne": "ES",
  "estonia": "EE",
  "estonie": "EE",
  "etats federes de micronesie": "FM",
  "etats-unis": "US",
  "ethiopia": "ET",
  "ethiopie": "ET",
  "falkland islands": "FK",
  "faroe islands": "FO",
  "federated states of micronesia": "FM",
  "federation de russie": "RU",
  "fidji": "FJ",
  "fiji": "FJ",
  "finland": "FI",
  "finlande": "FI",
  "france": "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  "gabon": "GA",
  "gambia": "GM",
  "gambie": "GM",
  "georgia": "GE",
  "georgie": "GE",
  "georgie du sud et les iles sandwich du sud": "GS",
  "germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "grece": "GR",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "grenade": "GD",
  "groenland": "GL",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guinee": "GN",
  "guinee equatoriale": "GQ",
  "guinee-bissau": "GW",
  "guyana": "GY",
  "guyane francaise": "GF",
  "haiti": "HT",
  "heard island and mcdonald islands": "HM",
  "honduras": "HN",
  "hong kong": "HK",
  "hong-kong": "HK",
  "hongrie": "HU",
  "hungary": "HU",
  "iceland": "IS",
  "ile bouvet": "BV",
  "ile christmas": "CX",
  "ile de man": "IM",
  "ile norfolk": "NF",
  "iles (malvinas) falkland": "FK",
  "iles aland": "AX",
  "iles caimanes": "KY",
  "iles cocos (keeling)": "CC",
  "iles cook": "CK",
  "iles feroe": "FO",
  "iles heard et mcdonald": "HM",
  "iles mariannes du nord": "MP",
  "iles marshall": "MH",
  "iles mineures eloignees des etats-unis": "UM",
  "iles salomon": "SB",
  "iles turks et caiques": "TC",
  "iles vierges britanniques": "VG",
  "iles vierges des etats-unis": "VI",
  "inde": "IN",
  "india": "IN",
  "indonesia": "ID",
  "indonesie": "ID",
  "iraq": "IQ",
  "ireland": "IE",
  "irlande": "IE",
  "islamic republic of iran": "IR",
  "islande": "IS",
  "isle of man": "IM",
  "israel": "IL",
  "italie": "IT",
  "italy": "IT",
  "jamahiriya arabe libyenne": "LY",
  "jamaica": "JM",
  "jamaique": "JM",
  "japan": "JP",
  "japon": "JP",
  "jordan": "JO",
  "jordanie": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kirghizistan": "KG",
  "kiribati": "KI",
  "koweit": "KW",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "l'ex-republique yougoslave de macedoine": "MK",
  "lao people's democratic republic": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "lettonie": "LV",
  "liban": "LB",
  "liberia": "LR",
  "libyan arab jamahiriya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "lituanie": "LT",
  "luxembourg": "LU",
  "macao": "MO",
  "madagascar": "MG",
  "malaisie": "MY",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "malte": "MT",
  "maroc": "MA",
  "marshall islands": "MH",
  "martinique": "MQ",
  "maurice": "MU",
  "mauritania": "MR",
  "mauritanie": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mexico": "MX",
  "mexique": "MX",
  "monaco": "MC",
  "mongolia": "MN",
  "mongolie": "MN",
  "montserrat": "MS",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "netherlands antilles": "AN",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norfolk island": "NF",
  "northern mariana islands": "MP",
  "norvege": "NO",
  "norway": "NO",
  "nouvelle-caledonie": "NC",
  "nouvelle-zelande": "NZ",
  "occupied palestinian territory": "PS",
  "oman": "OM",
  "ouganda": "UG",
  "ouzbekistan": "UZ",
  "pakistan": "PK",
  "palaos": "PW",
  "palau": "PW",
  "panama": "PA",
  "papouasie-nouvelle-guinee": "PG",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "pays-bas": "NL",
  "perou": "PE",
  "peru": "PE",
  "philippines": "PH",
  "pitcairn": "PN",
  "poland": "PL",
  "pologne": "PL",
  "polynesie francaise": "PF",
  "porto rico": "PR",
  "portugal": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "republic of korea": "KR",
  "republic of moldova": "MD",
  "republic of the congo": "CG",
  "republique arabe syrienne": "SY",
  "republique centrafricaine": "CF",
  "republique de coree": "KR",
  "republique de moldova": "MD",
  "republique democratique du congo": "CD",
  "republique democratique populaire lao": "LA",
  "republique dominicaine": "DO",
  "republique du congo": "CG",
  "republique islamique d'iran": "IR",
  "republique populaire democratique de coree": "KP",
  "republique tcheque": "CZ",
  "republique-unie de tanzanie": "TZ",
  "reunion": "RE",
  "romania": "RO",
  "roumanie": "RO",
  "royaume-uni": "GB",
  "russian federation": "RU",
  "rwanda": "RW",
  "sahara occidental": "EH",
  "saint helena": "SH",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "saint-kitts-et-nevis": "KN",
  "saint-marin": "SM",
  "saint-pierre and miquelon": "PM",
  "saint-pierre-et-miquelon": "PM",
  "saint-siege (etat de la cite du vatican)": "VA",
  "saint-vincent-et-les grenadines": "VC",
  "sainte-helene": "SH",
  "sainte-lucie": "LC",
  "samoa": "WS",
  "samoa americaines": "AS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "sao tome-et-principe": "ST",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia and montenegro": "CS",
  "serbie-et-montenegro": "CS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "singapour": "SG",
  "slovakia": "SK",
  "slovaquie": "SK",
  "slovenia": "SI",
  "slovenie": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "somalie": "SO",
  "soudan": "SD",
  "south africa": "ZA",
  "south georgia and the south sandwich islands": "GS",
  "spain": "ES",
  "sri lanka": "LK",
  "sudan": "SD",
  "suede": "SE",
  "suisse": "CH",
  "suriname": "SR",
  "svalbard and jan mayen": "SJ",
  "svalbard etile jan mayen": "SJ",
  "swaziland": "SZ",
  "sweden": "SE",
  "switzerland": "CH",
  "syrian arab republic": "SY",
  "tadjikistan": "TJ",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tchad": "TD",
  "terres australes francaises": "TF",
  "territoire britannique de l'ocean indien": "IO",
  "territoire palestinien occupe": "PS",
  "thailand": "TH",
  "thailande": "TH",
  "the democratic republic of the congo": "CD",
  "the former yugoslav republic of macedonia": "MK",
  "timor-leste": "TL",
  "togo": "TG",
  "tokelau": "TK",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "trinite-et-tobago": "TT",
  "tunisia": "TN",
  "tunisie": "TN",
  "turkey": "TR",
  "turkmenistan": "TM",
  "turks and caicos islands": "TC",
  "turquie": "TR",
  "tuvalu": "TV",
  "u.s. virgin islands": "VI",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united republic of tanzania": "TZ",
  "united states": "US",
  "united states minor outlying islands": "UM",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "vatican city state": "VA",
  "venezuela": "VE",
  "viet nam": "VN",
  "vietnam": "VN",
  "wallis and futuna": "WF",
  "wallis et futuna": "WF",
  "western sahara": "EH",
  "yemen": "YE",
  "zambia": "ZM",
  "zambie": "ZM",
  "zimbabwe": "ZW",
};
export default countryNameToIso;